### PR TITLE
Modernize the code

### PR DESCRIPTION
**Pull request by Schniz**
* Use newer React
* Use TypeScript because everybody likes TypeScript
* Use Parcel for bundling (maybe use microbundle?)

### CODE REVIEW

**Comment by Schniz** [comment]
Using `microbundle` looks appealing to me for distributing the library (more than using `parcel`), but it seems that the `umd` export for React doesn't work well. It tries to fetch `window.react` instead of `window.React`, which causes an error

**Comment by Schniz** [comment]
On another note, though it will probably be out of the scope for this PR, The current API is:

```jsx
<Menu menuItems={[{ className: "fa fa-twitter", title: "Twitter" }]} />
```

But I'd rather have the following API, to support more components:

```jsx
<Menu>
  <Item title="Twitter" className="fa fa-twitter" component={Link} to="..." />
</Menu>

**Comment by Schniz** [comment]
alright, the current api is:

```jsx
<Menu>
  <Item title="Hello!" component="a" componentProps={{href: "https://fb.com" }}>
    Here's anything you want, probably <Icon />?
  </Item>
</Menu>
```

`component` is `a` by default, `componentProps` isn't mandatory as well.

**Comment by Schniz** [comment]
Hey @KPSoftec, @sjollois and @Jromero97 👋 

what do you think about the API suggestion in this PR?

You can see the full README here ->
https://github.com/Schniz/react-gooey-nav/blob/modernize/README.md

**Comment by Jromero97** [comment]
@Schniz That's look pretty cool, I'll try on my project and I give you feedback, btw: I don't like TypeScript xD, I prefer ES6, I hope that's not be a problem with the resource.

**Comment by Schniz** [comment]
Well, TypeScript isn't my type either ;p but it's better than nothing in terms of maintainability.
I considered using Flow but it seems like the community likes TS more, so it's fine with me 😸

**Pull request merged**
